### ISSUE TITLE
Support customization of the root path in Zookeeper

### ISSUE THREAD

**Issue by WadeWaldron** [typesafehub/constructr-zookeeper#18]
Currently the plugin only supports the path of: /constructr/{clustername}

It would be nice if this was customizable to some extent so that you could do things like:

/someprefix/{clustername}
or
/someprefix/constructr/{clustername}

**Comment by markusjura** [comment]
I'd like to understand why is this desirable?

A cluster name is basically the actor system, and this should serve as the unique identifier. An actor system needs to be unique within the same infrastructure anyway.

If an additional prefix is necessary, then this should be an addition to [constructr](https://github.com/hseeberger/constructr) and not only to constructr-zookeeper so that it applies for all coordination service implementations. Note that the default etcd service coordination service is not using a prefix as well: https://github.com/hseeberger/constructr/blob/master/constructr-coordination-etcd/src/main/scala/de/heikoseeberger/constructr/coordination/etcd/EtcdCoordination.scala#L71

Note that in the commit https://github.com/hseeberger/constructr/commit/db0f6297b19abd48e1bf6da148c1bfd0980f3b47 a prefix of the base path has been removed. Originally a prefix was used to distinguish between an Akka or Cassandra cluster. Hence constructr dropped cassandra support the prefix was removed.

**Comment by WadeWaldron** [comment]
In this specific case, we have a zookeeper instance that is being shared by multiple groups. It has been requested by the maintainers of that zookeeper instance that users of zookeeper provide their own top level path to distinguish from other users of the zookeeper.

More generally, I think a default value of /constructr is fine, but I can imagine cases where other companies or groups may have a need to customize this to meet with specific guidelines (such as the one above).

**Comment by markusjura** [comment]
Ok, feel free to add a PR for it. Note that this does not apply only for ZK, so PRs for the other coordination service would then make sense as well. Also to keep them consistent. By default, the prefix should be empty so that `constructr/my-actor-system` is used.
